### ISSUE TITLE
CSimpleIniW is unable to read the desktop.ini

### ISSUE THREAD

**Issue by LubosPintes** [brofield/simpleini#10]
Just tried to read the desktop.ini in the "Documents" folder.
I used CSimpleIniW for this, this file is in UTF-16. Nothing was read, I tried to iterate through the section names.

**Comment by brofield** [comment]
This might be due to a permissions error. Please investigate the problem
further and create a more complete problem description.

Regards,
Brodie

**Comment by LubosPintes** [comment]
The desktop.ini in Documents folder is readable. So I believe this is 
not a permission problem.
Here is short snippet:
CSimpleIniW ini;
SI_Error err=ini.LoadFile("c:\\users\\username\\documents\\desktop.ini");
if(err!=SI_OK) {
   cout<<"Error loading ini file"<<endl;
} else {
   CSimpleIniW::TNamesDepend names;
   ini.GetAllSections(names);
   for(CSimpleIniW::TNamesDepend::iterator i=names.begin(); 
i!=names.end(); ++i) wcout<<i->pItem<<endl;
}

Just before this, I tried the GetValue method. It didn't work, so I 
tried the above snippet to test more.

Dňa 2. 3. 2015 o 11:53 Brodie Thiesfield napísal(a):
> This might be due to a permissions error. Please investigate the problem
> further and create a more complete problem description.
>
> Regards,
> Brodie
>

**Comment by brofield** [comment]
This is still not a bug report. You give no test data, you give no
indication of where it fails, nor how it fails. You are a programmer, so
you must know what a bug report is -- write one.
http://www.chiark.greenend.org.uk/~sgtatham/bugs.html

Better yet, seeing as it is a single file, not so hard to understand, and
with plenty of comments, step into the failing method and see if you can
diagnose the fault.

You have not convinced me as yet that the fault is in this library.

**Comment by LubosPintes** [comment]
Ok, I dived into the implementation of this library and I realized that 
this is indeed not a bug. It is simply not designed to work with UTF-16 
encoded files. I was confused a bit with "W" suffix of CSimpleIni class.
I suggest to close this as invalid.


Dňa 2. 3. 2015 o 14:28 Brodie Thiesfield napísal(a):
> This is still not a bug report. You give no test data, you give no
> indication of where it fails, nor how it fails. You are a programmer, so
> you must know what a bug report is -- write one.
> http://www.chiark.greenend.org.uk/~sgtatham/bugs.html
>
> Better yet, seeing as it is a single file, not so hard to understand, and
> with plenty of comments, step into the failing method and see if you can
> diagnose the fault.
>
> You have not convinced me as yet that the fault is in this library.
>
>

**Comment by brofield** [comment]
Ah yes. The interface can be wide char, however the loading/saving doesn't handle it, however it shouldn't be difficult to add a UTF16 load/save interface to it if you were that way motivated.
