### ISSUE TITLE
Issues by including windows.h

### ISSUE THREAD

**Issue by scorpeeon** [brofield/simpleini#11]
SimpleIni includes windows.h in a header file (SimpleIni.h:3248) which can cause several issues.
windows.h has macros polluting the global namespace.

So for instance when I was trying to use a standard C++11 function: std::numeric_limits<int>::max() it wouldn't compile, because windows.h already defined it (through minwindef.h) and it takes precedence over the standard function I was trying to use.

The particular issue I ran into can be fixed by placing
#define NOMINMAX
just before including <windows.h> in SimpleIni.h (and placing #undef NOMINMAX afterwards).

Defining/undefing WIN32_LEAN_AND_MEAN in a similar fashion could also reduce the garbage that gets included with windows.h.

But for the long term, it might be better, if windows.h wouldn't have to be included in the header in the first place. This should be a small little cross-platform code handling ini files, and including windows.h itself can be quite disruptive.

**Comment by brofield** [comment]
I agree that not including windows.h would be best, however I don't have access to a build environment at the moment, so I can't see what dependencies it has. Probably every call to the win32 API. Def/undef of those defines would have to be conditional on if we defined them in the first place. If you want to submit a patch then I am happy to look at it.

**Comment by scorpeeon** [comment]
Thanks for the quick response. Created a pull request with a conditional version of the NOMINMAX define, this should fix the problem that I've encountered.
Thought about also defining WIN32_LEAN_AND_MEAN but that along with NOMINMAX would complicate the conditional define cases (to 4 conditional cases instead of 2), so I didn't include that for now. For the long run it would be really the best if we could get rid of windows.h anyway, then no such defines would be needed.

Also I read a useful writing about this here, might be worth considering: http://stackoverflow.com/questions/1394132/macro-and-member-function-conflict

"The only really general solution is to not include windows.h in your headers.

That header is a killer, and does pretty much anything it can to make your code blow up. It won't compile without MSVC language extensions enabled, and it is the worst example of macro abuse I've ever seen.

Include it in a single .cpp file, and then expose wrappers in a header, which the rest of your code can use. If windows.h isn't visible, it can't conflict with your names.

For the min/max case specifically, you can #define NOMINMAX before including windows.h. It will then not define those specific macros."

**Comment by brofield** [comment]
Thanks for the pull request, but I don't like the proposed change.

Essentially, my inclusion of windows.h is a bandaid for projects that have not included it themselves. I could remove it from the header, but then I would get people banging on about compilation errors due to them forgetting to include it themselves. If the user has not dragged it into the project themselves already (which they should have in the PCH), then I will include it for them.

So I think the better solution is to define NOMINMAX / LEAN_AND_MEAN when I include windows.h, but guard the include with a check.

e.g.
// We need the Win32 API, so if we don't already have it, then include it on our terms. 
// If you don't like our terms, then include windows.h yourself prior to including simpleini.h
#ifndef WINDOWS_H   (whatever this is)
# define NOMINMAX
# define WIN32_LEAN_AND_MEAN
# include <windows.h>
#endif

If you code up this solution I will accept it.

**Comment by scorpeeon** [comment]
I see, so you would guard the whole include (not only the NOMINMAX define - which could otherwise be defined twice which would cause a warning at compiling).
I'm not sure I see what the problem is though with the minor changes I proposed.
But if we're going on another way, I still think the best solution would be - as suggested on stackoverflow - to make the header free of including windows.h (and the Windows-dependent APIs), and move it to a single cpp, so it wouldn't be visible at all to anything that includes SimpleIni.h, so it wouldn't conflict neither with min()/max(), nor with anything else (that it otherwise very well could).
As I understand, windows.h is only needed in a small part of the code (the SI_CONVERT_WIN32 block, which is about 160 lines out of 3400+) that is not even used at all on any other platform than Windows (and even there it's not always used), so moving it to a cpp shouldn't be very hard. Or is there something I don't see?

**Comment by brofield** [comment]
It is only included if SI_CONVERT_WIN32 is defined, which is defined by default on Windows and obviously other platform. You have the option of ignoring that conversion method and using the generic or ICU converters. If you do use the WIN32 converter, then you are on Windows, using the win32 API, and should be including windows.h, most likely in your pre-compiled headers. If you wish to use any sort of specific definitions prior to including windows.h, then you are able to do this prior to including simpleini. e.g.

    #define NOMINMAX
    #include <windows.h>
    ....
    #include "simpleini.h"
