### ISSUE TITLE
Use of _WIN32 define instead of _MSC_VER breaks build with other Windows compilers

### ISSUE THREAD

**Issue by 1Conan** [brofield/simpleini#14]
Read this
http://stackoverflow.com/questions/23343080/c-to-c11-in-gcc-mingw-missing-function

**Comment by brofield** [comment]
This is a bit lazy.

Rename the issue to something reasonable, supply proper details and a since
you've obviously already got a fixed for it, supply a pull request.

Thanks.

**Comment by 1Conan** [comment]
Well its 12AM when i posted it i couldnt make a proper post that ime

**Comment by brofield** [comment]
This fix won't work. It changes defines that should not be changed and breaks the Linux build. It appears to be just a blanket _WIN32 to _MSC_VER search and replace. I expect that you would at least critically evaluate each change to ensure that it is relevant and correct. Feel free to submit again when you have done so.
