### ISSUE TITLE
LoadFile() fails on empty file with Unicode, UTF-8

### ISSUE THREAD

**Issue by leokoppel** [brofield/simpleini#19]
Ran into this when trying a simple "will this compile and run?" without anything in the ini file. `SI_CONVERT_WIN32` is set.

    const PWSTR filename= L"empty.ini";

    CSimpleIniW ini(true, false, false);
    
    // Write empty file
    SI_Error retval = ini.SaveFile(filename);
    assert(retval == SI_OK);

    // Attempt to load empty file - fails
    retval = ini.LoadFile(filename);
    assert(retval == SI_FAIL);

The problem seems to be in the Windows version of `SizeFromStore` for that combination of flags. It calls [`MultiByteToWideChar`](https://msdn.microsoft.com/en-ca/library/windows/desktop/dd319072(v=vs.85).aspx) with a `cbMultiByte` of 0, which fails.

I'll see if there's a safe simple fix but I'm not familiar with these character set functions. Otherwise, this may at least help someone else who runs into the issue.

**Comment by brofield** [comment]
Thanks for your patch.
