### ISSUE TITLE
C++ to C++11 in gcc MinGW Microsoft function

### ISSUE THREAD

**Issue by SimpleInic11Bug** [brofield/simpleini#23]
https://stackoverflow.com/questions/23343080/c-to-c11-in-gcc-mingw-missing-function

**Comment by brofield** [comment]
Use either SI_CONVERT_GENERIC or SI_CONVERT_ICU. 

It is not as simple as just changing _WIN32 to _MSC_VER. If you want to provide a patch for enabling conversion using the win32 api but maintaining compatibility with mingw then please go ahead.
