### ISSUE TITLE
SetUnicode reading problem

### ISSUE THREAD

**Issue by florgeng** [brofield/simpleini#25]
I create a file file unicode markup.
Then I want to read it. But this works only, when I tell the instance that a unicode file will be opened.
I thought the parser will notice and care about the BOM.

```
#include <iostream>
#include "SimpleIni.h"


int main()
{
#define section "sec"
#define val "value"
#define file "/tmp/file.ini"

  CSimpleIniA writer;
  writer.SetUnicode();
  long value = 10;
  writer.SetLongValue(section,val,value);
  writer.SaveFile(file);

  CSimpleIniA DontWork;
  DontWork.LoadFile(file);
  std::cout<<DontWork.GetLongValue(section,val)<<std::endl;

  CSimpleIniA Work;
  Work.SetUnicode();
  Work.LoadFile(file);
  std::cout<<Work.GetLongValue(section,val)<<std::endl;
}
```

the content of the created file is:
HEX: 
`EF BB BF 5B 73 65 63 5D 0A 76 61 6C 75 65 20 3D 20 31 30 0A`
ASCII:
`[sec]
value = 10`

**Comment by brofield** [comment]
The library assumes that if you are loading your own files you know if you are expecting unicode data. However, the latest version will now load the file according to your test.
