### ISSUE TITLE
Allow empty string (eg. "" ('\0')) as valid comment for AddEntry function

### ISSUE THREAD

**Issue by KerstinKeller** [brofield/simpleini#27]
Is it possible to allow "" to be a valid comment for any of the ini file setter functions?
Right now, it seems that only NULL or a char sequence starting with ';' or '#' may be used as a comment.
Passing to "" to SetValue ends in a failing assertion

```
SI_ASSERT(!a_pComment || IsComment(*a_pComment));
```

A solution could be to define

```
/** Does the supplied character start a comment line? */
inline bool IsComment(SI_CHAR ch) const {
    return (ch == ';' || ch == '#' || ch == '\0');
}
```

I am not quite sure if anything else will have to be changed for this to work correctly.

**Comment by brofield** [comment]
To add a comment to a line you need to provide the comment line in full comment format, e.g. start the comment with a comment character. "# my comment". 

What is the reason that you want to be able to use an empty string?
