### ISSUE TITLE
Any planned release after 4.17?

### ISSUE THREAD

**Issue by f-camera** [brofield/simpleini#29]
Hi all,
thanks for the project value.
Is there any plan to issue a "tagged" version after 4.17? I saw there are some modifications after the most recent release.
Thank you in advance.

**Comment by fatrolls** [comment]
it's already past 4.2 (back in 2008)

http://read.pudn.com/downloads133/sourcecode/windows/other/565651/simpleini/testsi.cpp__.htm

**Comment by brofield** [comment]
In the midst of updating it now with a test harness. Trouble getting the test harness to build on linux. Once that is done I'll create a new release.
