### ISSUE TITLE
Ini without '=' : is that possible?

### ISSUE THREAD

**Issue by jaromrax** [brofield/simpleini#32]
Thanks for the code. I have a rather a question than an issue - my files (generated by somebody else) are without equal signs:
```
[COMMON]
OPEN USB 0 0
GNUPLOT_PATH ""

[0]
ENABLE_INPUT           YES
DC_OFFSET              0
TF_DECAY_TAU 50.0
TRG_THRESHOLD 101
```
Comments begin with #.   Can I use **simpleini** for this ? My basic attempt didnt work.
Thank you.
 Jaro

**Comment by brofield** [comment]
There is a pull request that looks like it might do what you want. Give it a go and let me know if it works for you. I am still considering adding it to the project.
