### ISSUE TITLE
simpleopt question

### ISSUE THREAD

**Issue by dallouche** [brofield/simpleini#38]
is it possible to use simpleinit for default option 
and overwrite this option in command line using simpleopt ?
sorry for this newbie question ?

**Comment by dallouche** [comment]
where can i found  a "simple" example ;)

**Comment by brofield** [comment]
There is none. The simplest way to do it is to use simpleini to load your config file and then use the in-memory ini file as the configuration. Use simpleopt to process the command line and update the in-memory ini file, that way any time you read config it will be either the defaults that you set, the values from the config file, or the values updated from the command line.
