### ISSUE TITLE
value returned by GetValue for multiline includes ENDTAG

### ISSUE THREAD

**Issue by mpuczynski** [brofield/simpleini#4]
Platform: Windows
Compiler: VS 2008, 32-bit

When getting a multi-line value for a key, GetValue() returns string that has the ENDTAG included. I get the same result when walking through TKeyVal of a section.
It happens only when ENDTAG is followed by white-space.

Regards,
Michal.

**Comment by brofield** [comment]
This behaviour was actually by design, however I have changed it now so that trailing whitespace after the ENDTAG is ignored. This has been fixed in the current file.
