### ISSUE TITLE
Errors on import

### ISSUE THREAD

**Issue by Valev008** [brofield/simpleini#41]
Hi. I downloaded this parser and put simpleIni.h, convertUTF.h and convertUTF.c in my project folder. When I run this code:

`
#ifdef _WIN32
#pragma warning(disable: 4786)
#endif

#ifdef _WIN32
#include <windows.h>
#define DELETE_FILE DeleteFileA
#else
#include <unistd.h>
#define DELETE_FILE unlink
#endif
#include <fstream>

#define SI_SUPPORT_IOSTREAMS

#include <iostream>
#include "SimpleIni.h"

using namespace std;

int main()
{
    return 0;
}
`

I get 4 errors:

> ||=== Build: Release in INIReader (compiler: GNU GCC Compiler) ===|
C:\Users\M0097932\Desktop\firstTest\INIReader\main.cpp|2|warning: ignoring #pragma warning  [-Wunknown-pragmas]|
C:\Users\M0097932\Desktop\firstTest\INIReader\SimpleIni.h||In member function 'SI_Error CSimpleIniTempl<SI_CHAR, SI_STRLESS, SI_CONVERTER>::LoadFile(const wchar_t*)':|
C:\Users\M0097932\Desktop\firstTest\INIReader\SimpleIni.h|1356|error: there are no arguments to '_wfopen' that depend on a template parameter, so a declaration of '_wfopen' must be available [-fpermissive]|
C:\Users\M0097932\Desktop\firstTest\INIReader\SimpleIni.h|1356|note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)|
C:\Users\M0097932\Desktop\firstTest\INIReader\SimpleIni.h||In member function 'SI_Error CSimpleIniTempl<SI_CHAR, SI_STRLESS, SI_CONVERTER>::SaveFile(const wchar_t*, bool) const':|
C:\Users\M0097932\Desktop\firstTest\INIReader\SimpleIni.h|2376|error: there are no arguments to '_wfopen' that depend on a template parameter, so a declaration of '_wfopen' must be available [-fpermissive]|
C:\Users\M0097932\Desktop\firstTest\INIReader\SimpleIni.h||In member function 'bool SI_NoCase<SI_CHAR>::operator()(const SI_CHAR*, const SI_CHAR*) const':|
C:\Users\M0097932\Desktop\firstTest\INIReader\SimpleIni.h|3271|error: there are no arguments to '_mbsicmp' that depend on a template parameter, so a declaration of '_mbsicmp' must be available [-fpermissive]|
C:\Users\M0097932\Desktop\firstTest\INIReader\SimpleIni.h|3275|error: there are no arguments to '_wcsicmp' that depend on a template parameter, so a declaration of '_wcsicmp' must be available [-fpermissive]|
||=== Build failed: 4 error(s), 1 warning(s) (0 minute(s), 0 second(s)) ===|

Can you help me?

**Comment by johlim** [comment]
> ||=== Build: Release in INIReader (compiler: GNU GCC Compiler) ===|

are you do compile  in windows platform ?

if so, consider visual studio compiler.

**Comment by Valev008** [comment]
I do, and I am stuck with the software my boss said I must use.

I found boost library ptree and ini_parser, so I'm good, but thank you for your help.

**Comment by johlim** [comment]
Well done, 
if you are considering an embedded system 
I would like to recommend "inih" https://github.com/benhoyt/inih

**Comment by Valev008** [comment]
Thanks. Tried inih as well, but got other errors when working with GUI app (https://github.com/benhoyt/inih/issues/75).
