### ISSUE TITLE
How to read multiple values?

### ISSUE THREAD

**Issue by vueltaconicarus** [brofield/simpleini#42]
I saw in the documentation that simpleini supports multiple values per key. I'd like to use this feature, but for the life of me I can't figure out how the ini file has to be written. 

I tried the following delimiters: " " (space), "," "|"
I tried the following brackets: none, (values), [values], {values}

So the question is: what syntax do you expect in the ini file, so that I can use the function "ini.GetAllValues("section-name", "key-name", values);"? The sample ini files don't appear to include an example...

**Comment by brofield** [comment]
Repeat the key. The key Phone in this example has multiple values.

[Owner]
Name=Joe
Phone=0405444888
Phone=0405666661

**Comment by vueltaconicarus** [comment]
Thanks, I got it working!
For future readers of this issue: The second important ingredient is to enable the option when inizializing the ini file:

bool a_bIsUtf8 = false, a_bUseMultiKey = true, a_bUseMultiLine = false;
CSimpleIniA ini(a_bIsUtf8, a_bUseMultiKey, a_bUseMultiLine);
