### ISSUE TITLE
memory leak problem

### ISSUE THREAD

**Issue by tianyaloveprogram** [brofield/simpleini#44]
I read all codes，and very like it .Then I have a suspicion that there is a memory leak at line 1318 . But I am not completely sure.So I want to ask for advice so that I will keep using it.
i.e,
if (!m_strings.empty()) {
        typename TNamesDepend::iterator i = m_strings.begin();
        for (; i != m_strings.end(); ++i) {
            delete[] const_cast<SI_CHAR*>(i->pItem);
        }
        m_strings.erase(m_strings.begin(), m_strings.end());
}
The member variable ,"pComment ",of the struct Entry  haven't be deleted.

**Comment by brofield** [comment]
The m_strings vector stores every pointer to allocated memory and deletes them all. When strings are copied using the CopyString method, they are added to this vector and removed using the code that you copied. There is no leak here. Thanks for looking into it though.
