### ISSUE TITLE
Release v4.18?

### ISSUE THREAD

**Issue by jlblancoc** [brofield/simpleini#46]
It would be useful to have a new stable release. In particular, I found a problem compiling with C++17 enabled, and found that the issue was already solved in #31 which is not included yet in any release.

**Comment by yurivict** [comment]
Last release was in 2013 (!!)

**Comment by brofield** [comment]
Completely agree. I have little spare time for programming these days. Last year I started adding a proper test harness using gtest but got held back when trying to get travis-ci integration going for Linux/Windows. I still would like to get this test harness running properly before releasing a full version.

**Comment by yurivict** [comment]
Please also add proper ```install``` target so that it would be possible to have it installed.

**Comment by brofield** [comment]
New release coming soon. No point having an install target. It is a single header file.

**Comment by viniciusferrao** [comment]
Hi @brofield I think the reason for adding a install target is to ease dependency managers.

**Comment by brofield** [comment]
I'm not sure exactly what you are wanting. Feel free to submit a pull request.
