### ISSUE TITLE
newline is '\\n' by GetValue for multiline

### ISSUE THREAD

**Issue by jackeykong** [brofield/simpleini#47]
I want to keep the newline is \r\n in windows, but now each line is delimited by a single '\\n' character,so how do i do that?

**Comment by brofield** [comment]
Internally, all newlines use \n. When you save to disk, all newlines will use either \n or \r\n as necessary. 

If you want to work with a multiline value then it will use \n only. You would need to convert it back to \r\n if that is what you want.

**Comment by jackeykong** [comment]
> Internally, all newlines use \n. When you save to disk, all newlines will use either \n or \r\n as necessary.
> 
> If you want to work with a multiline value then it will use \n only. You would need to convert it back to \r\n if that is what you want.

thank you
