### ISSUE TITLE
loop bug

### ISSUE THREAD

**Issue by 0o7x** [brofield/simpleini#50]
I don't know if this project still alive but i have the following problem

I'm trying to read some ini files multiple times in my program but after two or three times it stop working
the file is loading correctly but i can't get any values
I only get (Null) back from GetValue 

any suggestion ?

**Comment by brofield** [comment]
It's still sort of alive. I wish it was more alive, but I don't have much
time these days to allocate to programming.

If you are able to look into the behaviour yourself and determine if it is
a bug, and if so provide a fix for it, then I'm happy to add it in.

Regards,
Brodie

**Comment by 0o7x** [comment]
I wish I had enough experience to fix it, but I'm still quite a beginner.
However I will do my best to fix it !

Thanks for your reply 
With all due respect

**Comment by brofield** [comment]
I hope that you solved your issue. Without more detail it is not possible to help you.
