### ISSUE TITLE
? instead of cyrillic symbols

### ISSUE THREAD

**Issue by Tommifninite** [brofield/simpleini#54]
Hello!
When I save cyrillic symbols(as a value) into my INI I get ������������_�������� instead of them.
Is it possible to save cyrillic symbols?
I tried omitting SetUnicode() or calling SetUnicode(1) with no success.

**Comment by brofield** [comment]
It works fine with unicode -- it was designed for unicode use. As long as
you are calling SetUnicode before using the object, and ensuring that
everything is properly encoded, it will work fine.You must be mixing your
encodings somewhere in your usage.

**Comment by Tommifninite** [comment]
Thanks, it turns out that  the text is actually saved fine - the actual problem is reading it with standart windows notepad.
Thanks!
And thanks for this wonderful library.
