### ISSUE TITLE
Fix CI Error

### ISSUE THREAD

**Issue by gamecss** [brofield/simpleini#56]
I done work of https://github.com/gamecss/simpleini-fix (may?)
sorry but my travis ci's credit only -370 now and I cannot test
should at least fix the Linux test

**Comment by brofield** [comment]
Thanks for your help. I made the changes but then fell down the rabbit hole of trying to get Travis working. I didn't realise that they had pulled the rug from OSS projects. Obviously years ago, but I have no time for dev at present. I've tried quickly to get Travis working but it seems that there are no credits available at Travis for free anymore even. I'll have to move it all away from Travis but that will have to wait unfortunately. Maybe in 6 months I'll quit my job and have time for OSS again. Again, thanks, but sorry I can't get this working just now.
