### ISSUE TITLE
Suggestion: Add Change Section Name API

### ISSUE THREAD

**Issue by wyz339** [brofield/simpleini#78]
In some case, need to change already existing section name, but keep original key value not changed.
So far I haven't found an interface in the library that does this, does the project have plans to support this interface?

**Comment by brofield** [comment]
You have all of the tools that you need. Iterate through the existing section, create the new section using the existing keys and values and delete the old section. Something like this...
https://chatgpt.com/share/674a4c6e-2a0c-800b-b12f-0d9814b187f3
